### ISSUE TITLE
Auto Captcha 

### ISSUE THREAD

**Issue by sunilgoudar** [suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking#1]
Hi Bro, Please implement auto captcha to book slot more faster. Entering captcha delays the booking process.. Rest all Good work.

**Comment by suraj-deshmukh** [comment]
@sunilgoudar  I have added support for auto captcha as well. It will still ask the user to verify the captcha as captcha solver might not give perfect results all the time. Captcha will get auto-populated on the captcha input text field.

![captcha](https://user-images.githubusercontent.com/14833831/120215401-4f185180-c253-11eb-891a-b0198bac3c22.png)
