### ISSUE TITLE
How to use by python

### ISSUE THREAD

**Issue by 520rahul** [suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking#10]
Brother can u plz make a video on how to use it by python.  I cant use docker as my system is on. Windows 7.  I have tried ur instructions but not able to undersrand

**Comment by suraj-deshmukh** [comment]
docker does not work in windows 7.

follow below link to install python on windows. it will also install pip.
[python on windows](https://www.ics.uci.edu/~pattis/common/handouts/pythoneclipsejava/python.html)

Once the installation is complete, you can either clone this repository to cowin-app(git is [required.](https://git-scm.com/download/win)) **OR** you can download this repository in [zip](https://github.com/suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking/archive/refs/heads/main.zip) format. 

If you download the zip format then unzip it and change folder name to **cowin-app**. After this step, open command line interface  and then `cd` to the `cowin-app` folder. Your current working directory should be `cowin-app` folder. and then run `pip install -r requirements.txt`. This will install all prerequisites.

Now `cd` to that folder where `cowin-app` folder is present and not inside the `cowin-app` folder. And run `bokeh serve --port 5100 cowin-app/` for manual mode and for auto mode run `bokeh serve --port 5100 cowin-app/ --args "you_gmail@gmail.com" "app_password_here"`

**Comment by 520rahul** [comment]
> docker does not work in windows 7.
> 
> follow below link to install python on windows. it will also install pip.
> [python on windows](https://www.ics.uci.edu/~pattis/common/handouts/pythoneclipsejava/python.html)
> 
> Once the installation is complete, you can either clone this repository to cowin-app(git is [required.](https://git-scm.com/download/win)) **OR** you can download this repository in [zip](https://github.com/suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking/archive/refs/heads/main.zip) format.
> 
> If you download the zip format then unzip it and change folder name to **cowin-app**. After this step, open command line interface and then `cd` to the `cowin-app` folder. Your current working directory should be `cowin-app` folder. and then run `pip install -r requirements.txt`. This will install all prerequisites.
> 
> Now `cd` to that folder where `cowin-app` folder is present and not inside the `cowin-app` folder. And run `bokeh serve --port 5100 cowin-app/` for manual mode and for auto mode run `bokeh serve --port 5100 cowin-app/ --args "you_gmail@gmail.com" "app_password_here"`
> 
> for auto mode please go through documentation

Thank u so much brother for explaining in this manner. I will tell us surely after installing the same using this method. Thanks again

**Comment by 520rahul** [comment]
@suraj-deshmukh thanks buddy i was able to run repo following ur instructions. I have 1 question if we are booking multiple beneficiaries then whether we have to write name of all the beneficiaries in name column or just 1 name and type beneficiaries id in its colums seperated by comma.

**Comment by suraj-deshmukh** [comment]
> @suraj-deshmukh thanks buddy i was able to run repo following ur instructions. I have 1 question if we are booking multiple beneficiaries then whether we have to write name of all the beneficiaries in name column or just 1 name and type beneficiaries id in its colums seperated by comma.

`name ` is just placeholder, so just put your name or anything. It does not matter at all what you put there. In case of multiple beneficiaries, use csv format like `12345678901234, 12345678901234`. for multple csvs use the same format `411002,411003` etc. 

**Note: beneficiary id is 14 digit long number**

**Note: select correct district where those pincodes belong. When you select state and district. Background thread pulls data from that district and filters the data using given pincodes.**

**Comment by 520rahul** [comment]
@suraj-deshmukh thanks buddy. I have starred ur repo.  Thanks again. I hope i vill b able to book slot using ur repo

**Comment by suraj-deshmukh** [comment]
@520rahul yes it works provided you have given all the input correct way. If you have selected manual way then stay alert to put otp in dashboard once you get otp on mobile and then click `Submit otp and book` button.
