### ISSUE TITLE
Feature request of beep/siren

### ISSUE THREAD

**Issue by 520rahul** [suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking#12]
@suraj-deshmukh i have an request that plz add a feature of beep sound or some siren when a slot is found and otp has been sent to the mobile number in case of manual otp system, as we will have to not keep our eyes on computer all the time and whenever beep sound comes v vill check mobile to enter otp

**Comment by 520rahul** [comment]
@suraj-deshmukh

**Comment by 520rahul** [comment]
@suraj-deshmukh did u add beep sound

**Comment by suraj-deshmukh** [comment]
> @suraj-deshmukh did u add beep sound

yes. updated the repo. can you please check and let me know if it works for you.

**Comment by 520rahul** [comment]
@suraj-deshmukh thanks brother. I shall let u know about beep sound working
