### ISSUE TITLE
New age group 18+

### ISSUE THREAD

**Issue by 520rahul** [suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking#13]
@suraj-deshmukh a new age group criteria 18+ has been introduced  which involves all person of age of 18+ But in repo there is only 2 options 18-44 and 45 above. Plz add this criteria also. And plz make beep sound setting to atleast for 10-15 seconds. Or if beep spund is configurable by us then plz tell me setting so that i can change it. Thirdly plz add sputnik in vaccine criteria. Only covaxin and covishield  are there in repo

**Comment by suraj-deshmukh** [comment]
https://github.com/suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking/blob/bb1c26b36afd03c6679c179cbd280a2c06ddc0cc/main.py#L255

you can change beep sound settings here.

I will update the repo soon with sputnik v and configurable beep sound.

**Comment by 520rahul** [comment]
@suraj-deshmukh boss plz update repo

**Comment by suraj-deshmukh** [comment]
> @suraj-deshmukh boss plz update repo

i am going through really busy scedule but i will try to add new group as soon as possible

**Comment by suraj-deshmukh** [comment]
> @suraj-deshmukh boss plz update repo

i have updated the repo with 18+ group and numeric input for beep duration and play beep button to simulate the beep sound.

**Comment by suraj-deshmukh** [comment]
@520rahul 
note: on cowin portal you can select multiple age groups and you will see the centers according to your selected age groups. 

In this dashboard you can only select single age group out of 3. so if you have selected age group as "18+", the script will only look into centers with 18+ group and remember 18+ group and 18-44 group centers are technically different. so make sure you  select the right age group.

I don't understand why govt has given 18+ group separately. It does not make sense at all.

**Comment by suraj-deshmukh** [comment]
@520rahul and if you were able to book slot successfully using this dashboard then you might want to give credit using [issues](https://github.com/suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking/issues/new?title=Booked%20Successfully&labels=success)

**Comment by 520rahul** [comment]
Thank u so much boss for helping us. U r doing a great job to the society. Hats off
