### ISSUE TITLE
Update in repo for 15-18 years and booster dose vaccine

### ISSUE THREAD

**Issue by 520rahul** [suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking#16]
Plz update repo according to new 15-18 age group and booster dose for others

**Comment by 520rahul** [comment]
@suraj-deshmukh plz reply

**Comment by suraj-deshmukh** [comment]
@520rahul hi Rahul, i wouldn't be able to make this change soon as I am already occupied with work.

**Comment by 520rahul** [comment]
@suraj-deshmukh plz make changes as for precaution dose also when u get the time.

**Comment by 520rahul** [comment]
@suraj-deshmukh its my humble request to kindly update the repo as slots in my area gone in seconds and theirs is no fixed time of slots opening.  Plz sir kindly consider my request it will b highly obliging to me because only your repo serves the purpose

**Comment by 520rahul** [comment]
@suraj-deshmukh

**Comment by suraj-deshmukh** [comment]
> @suraj-deshmukh its my humble request to kindly update the repo as slots in my area gone in seconds and theirs is no fixed time of slots opening.  Plz sir kindly consider my request it will b highly obliging to me because only your repo serves the purpose

Will try to add within 2 3 days

**Comment by 520rahul** [comment]
@suraj-deshmukh thanks a ton sir

**Comment by 520rahul** [comment]
@suraj-deshmukh sir i have observed their are 3 types of age groups on cowin portal:-
1. Age 15+ which covers all 15+ person
2. Age 15-18 which covers all person of age grp between 15 to 18
3. Age 18+ which covers all 18+ person

Point 1. Age group is not general filter but it is available in certai. Centres.

**Comment by suraj-deshmukh** [comment]
Thanks for this info. I am working on the same change. I am already
occupied with some work so expect some delay

**Comment by 520rahul** [comment]
@suraj-deshmukh thanks a lot sir.  I m eagerly waiting for ur repo. 😀

**Comment by suraj-deshmukh** [comment]
@520rahul  i have updated the repo for booster dose and dose for 15 age group. please check.

**Comment by 520rahul** [comment]
A big thanks to u sir from bottom of my heart. Thanks a lot for sparing your time inspite of having other priorities. Gid bless u
