### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by hpk22** [suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking#3]
I request to add functionality of auto otp using some otp retriever app. Also auto captcha as slots in metro cities are running out very quick.

**Comment by suraj-deshmukh** [comment]
@hpk22 

I did few improvements recently. There are two modes available now i.e Auto and Manual. In Auto mode everything is automated. Unlike other booking scripts/utilities, the user does not need to feed otp every now and then. You can go through the documentation about how it works.
