### ISSUE TITLE
Booked Successfully.

### ISSUE THREAD

**Issue by sunilgoudar** [suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking#4]
Used Docker method to book my appointment.

**Bro i have some suggestion..**

1. Make otp verification before finding slot. And put a timer for 15 minutes to regenerate OTP.  Because after finding the available slot it take few seconds to submit otp and in that few seconds the slot gets over. So make OTP generation during submit information.

2. After submiting OTP.. fetch beneficiary REF ID and make a drop down box or check box to select beneficiary. It will make more easier for user to use.

**_Rest all is fine. Thanks for your efforts and helping people to get their slot booked._**

![Capture](https://user-images.githubusercontent.com/60724779/120371034-e902fb80-c332-11eb-977f-e3a71b3a11d7.JPG)

**Comment by suraj-deshmukh** [comment]
Hi

I am glad that this helped you to book an appointment. 

About your suggestions, there are other scripts which offer full automation but those require a lot of initial setups and it comes with it own pitfalls. I wanted to keep it simple. Though I am thinking of automating OTP as well with bare minimum setup. There are existing SMS forwarding apps that can be used to forward SMS to email and then having email monitoring at the server-side would help . To poll the availability we really don't need to log in. The more we try to automate the more complications we add. This is why I am keeping it simple.

**Comment by suraj-deshmukh** [comment]
@sunilgoudar 

I did few improvements recently. There are two modes available now i.e Auto and Manual. In Auto mode everything is automated. Unlike other booking scripts/utilities, the user does not need to feed otp every now and then. You can go through the documentation about how it works.
