### ISSUE TITLE
What refresh rate it uses

### ISSUE THREAD

**Issue by 520rahul** [suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking#9]
What is default refresh rate. And can v change it

**Comment by suraj-deshmukh** [comment]
it is 3 seconds. from dashboard you can't but you can always edit code.

**Comment by suraj-deshmukh** [comment]
but don;t change the rate. 3 seconds works perfectly fine even if you keep checking all day. that's how i have designed this so that even if you keep it ON all day you should not get blocked by cowin server

**Comment by 520rahul** [comment]
> but don;t change the rate. 3 seconds works perfectly fine even if you keep checking all day. that's how i have designed this so that even if you keep it ON all day you should not get blocked by cowin server

Can u describe where to change code. Plz guide

**Comment by suraj-deshmukh** [comment]
> > but don;t change the rate. 3 seconds works perfectly fine even if you keep checking all day. that's how i have designed this so that even if you keep it ON all day you should not get blocked by cowin server
> 
> Can u describe where to change code. Plz guide

here. change the time.sleep(3) to time.sleep(n), n will be your choice number

https://github.com/suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking/blob/8ee91407ded148cae6406aa99e44fc90c1b8a349/main.py#L96

The api that I am using if findBy api. Its a real time data api not the cache one.

If you keep sleep time less than 3 seconds you will end up getting blocked by server.

**Comment by 520rahul** [comment]
> > > but don;t change the rate. 3 seconds works perfectly fine even if you keep checking all day. that's how i have designed this so that even if you keep it ON all day you should not get blocked by cowin server
> > 
> > 
> > Can u describe where to change code. Plz guide
> 
> here. change the time.sleep(3) to time.sleep(n), n will be your choice number
> 
> https://github.com/suraj-deshmukh/CoWin-Vaccine-Slot-Monitoring-and-Auto-Booking/blob/8ee91407ded148cae6406aa99e44fc90c1b8a349/main.py#L96
> 
> The api that I am using if findBy api. Its a real time data api not the cache one.
> 
> If you keep sleep time less than 3 seconds you will end up getting blocked by server.

Thanks a ton brother
